yolo_detect:
  ros__parameters:
    feed_type: 0
    yolo_detect_config_file: "config.json"
    image: "test.jpg"
    pushlisher_node_name: "Point_msg"
    subscription_node_name: "Camera_Image"

mipi_camera_path:
  ros__parameters:
    publisher_img_topic_name: "image_raw"
    publisher_compressimg_topic_name: "image_raw/compress_img"

HDMI_Display:
  ros__parameters:
    image_rendering: 1
    subscription_yolo_topic_name: "image_raw"
    subscription_img_topic_name: "yolo_detections"